### PR TITLE
Updated astronomy and transfers docs

### PR DESCRIPTION
**Pull request by Jordatious**
Updated HDF5 conversion section with new slow-mode syntax. Added two sentences about eligible ilifu MeerKAT projects. Added to Globus docs about internal ilifu transfers, symlinks and repairing them with rsync.

### CODE REVIEW

**Comment by jeremysmith123** [comment]
I am happy with these changes and think the PR can be merged.

**Comment by daikema** [comment]
so `ilifu-astro-*` and CARTA ... is the filtering indeed done on a wildcard basis like that, or is the notion that all in `ilifu-astro-*` will also be in `idia-group`?

Am still not a major fan of using DTNs to migrate data between filesystems - for non-standard stuff would much rather see `getfacl` / `setfacl` added to the docs instead.  At the moment don't think it'll have a massive impact on throughput for WAN transfers, as most production transfers use a different node.

... but I see you merged while i was typing this comment

**Comment by Jordatious** [comment]
@jeremysmith123 thinks `getfacl` / `setfacl` is a bit too low level, and that people will ask us if necessary. Right now I don't believe `ilifu-astro-*` is being considered, but we're going to raise that. Those in `ilifu-astro-*` aren't necessarily in `idia-group`.

I did discourage using the DTN for transfers between filesystems. Perhaps as an alternative we can add docs about using a screen / tmux / mosh session to do long-standing transfers on transfer@ilifu.ac.za?

**Comment by daikema** [comment]
One reason why I'd suggest including `getfacl` / `setfacl` - even if listing it as an advanced topic would be to have users not do things like make their directories globally writable.  Or perhaps we could add something on groups and procedures to request new Ilifu groups, with a warning that you shouldn't make your dirs world-writable.  (Could just link to some separate docs on get/set ACLs as an advanced use case perhaps?)

If `ilifu-astro-*` is being considered but is not yet in practice, then perhaps its addition to the docs should be deferred to layer?  Am not quite sure that it's advisable though to move to that wildcard approach, as I suspect that the system will need enumeration turned on to get all the groups listed which is what was causing LDAP problems before.  (That said, if this is done by directly querying LDAP rather than via PAM, this may or may not avoid those problems ... not quite sure how this is handled for a single-user rather than doing this system-wide).

I'm not sure how adding a section named `#### Using Globus for internal ilifu transfers` to the docs counts as discourage using the DTN for transfers between filesystems.  Were you thinking of the discouragement of using the SLURM login node instead?

**Comment by Jordatious** [comment]
> One reason why I'd suggest including `getfacl` / `setfacl` - even if listing it as an advanced topic would be to have users not do things like make their directories globally writable. Or perhaps we could add something on groups and procedures to request new Ilifu groups, with a warning that you shouldn't make your dirs world-writable. (Could just link to some separate docs on get/set ACLs as an advanced use case perhaps?)

I think I generally agree it's not a bad idea. I know Krishna uses it. Do you want to have a crack?

> If `ilifu-astro-*` is being considered but is not yet in practice, then perhaps its addition to the docs should be deferred to layer? Am not quite sure that it's advisable though to move to that wildcard approach, as I suspect that the system will need enumeration turned on to get all the groups listed which is what was causing LDAP problems before. (That said, if this is done by directly querying LDAP rather than via PAM, this may or may not avoid those problems ... not quite sure how this is handled for a single-user rather than doing this system-wide).

Not really sure what you're saying but this is now in place.

> I'm not sure how adding a section named `#### Using Globus for internal ilifu transfers` to the docs counts as discourage using the DTN for transfers between filesystems. Were you thinking of the discouragement of using the SLURM login node instead?

If you read the actually text it says:

> However, the performance (< 100 MB/s) is comparable to running `cp`, `mv`, `rsync` or `scp` on transfer@ilifu.ac.za.

I still think there's reason to use it in terms of volatility of large transfers and other features like monitoring and emailing and checksum, etc. But if it's going to be an issue for the DTN we could maybe document alternative ways to do large transfers, which I would suggest is done on a SLURM node, which gives you most of those same features.

**Pull request merged**
