### PR TITLE
Add Simba docs

### PR DESCRIPTION
**Pull request by Jordatious**

### CODE REVIEW

**Comment by jeremysmith123** [comment]
Only concern about adjusting the heading sizes is what it will do to the SARAO data transfers link that we have given to SARAO archive for the help guide.

Otherwise everything else seems fine.

**Comment by Jordatious** [comment]
@jeremysmith123 changing heading sizes doesn't change the links, although changing title will. So you gave them [this](http://docs.ilifu.ac.za/#/astronomy/astronomy_software?id=transfer-data-from-the-sarao-archive) link (rather than the one of the transfers page)? Is it too late to change? We can change it back.

**Comment by Jordatious** [comment]
I've changed it back for now

**Comment by jeremysmith123** [comment]
I'd have to check with Chris, the doc hasn't been updated on the archive, but it might be going through a review process. If we could leave the title as it is that would be preferable.

**Comment by Jordatious** [comment]
That's cool I've changed it back now and checked the link, so we can merge if you're happy.

**Pull request merged**
